### PR TITLE
Change Requirements to silverstripe/framework rather than silverstripe/cms

### PR DESCRIPTION
**Pull request by UndefinedOffset**
This pull request changes the requirement of silverstripe/cms to silverstripe/framework I don't see a reason for this to be locked to requiring the cms opening up to just requiring the framework allows for non-cms projects to use this.

### CODE REVIEW

**Comment by Firesphere** [comment]
I agree. Could you please have a look at the error happening on Travis? It looks fairly minor

**Comment by Firesphere** [comment]
I think the CircleCI config needs a bit of an update :)

**Comment by UndefinedOffset** [comment]
There seems to be 2 issues happening, one is that the dev branches for `silverstripe/recipe-cms` no longer exist for 1.0.x and 1.1.x, so should the tests be removed for them or updated so it pulls a stable release. The second issue I'm not sure why it's happening honestly :) it seems to be an issue connecting to the database's, not just MySQL but postgres as well.

**Comment by robbieaverill** [comment]
Hi @undefinedoffset, you can fix the branch problem by changing to 4.2.x-dev as the lowest value, the older branches were deleted recently. The DB issue can be fixed by specifying `dist: trusty`, since the new default xenial doesn’t include everything trusty did by default

**Comment by UndefinedOffset** [comment]
Ahhhhh... good call @robbieaverill I never thought to check if they changed the base build, so used to Travis CI Pro it hasn't switched yet. I did as you suggested and things are passing now. I also added a 5.6 test against 4.2 just so that legacy PHP version is covered.

**Pull request merged**
