### PR TITLE
Add `many_many_through` relations

### LINKED ISSUE #89: Support for SS4 many_many joined on a separate DataObject
The annotator does not work with the new many_many through relationship joined on a separate DataObject. See [](https://docs.silverstripe.org/en/4/developer_guides/model/relations/).

You can now use an extra DataObject to define a many many relation:
```
 private static $many_many = [
    "Supporters" => [
      'through' => 'TeamSupporter',
      'from' => 'Team',
      'to' => 'Supporter',
    ]
  ];
```

Unfortunatly the module can not resolve this new format

### PR DESCRIPTION
**Pull request by Firesphere**
Resolves #89

### CODE REVIEW

**Comment by robbieaverill** [comment]
Looks like the tests failed, but the changes look great!

**Comment by Firesphere** [comment]
ARGH, the tests failed due to a typo! Should be fixed on this run

**Comment by Firesphere** [comment]
A few irrelevant changes, like use statements and ignores added as well, to be able to properly run tests locally and such. Those aren't functional changes.

**Comment by robbieaverill** [comment]
I just noticed that the tests for this are in has_many, I'm moving it now

**Pull request merged**
