### PR TITLE
do not remove empty lines

### PR DESCRIPTION
**Pull request by lekoala**
the current regex is too greedy and remove empty lines that make the code breathes :-)

### CODE REVIEW

**Comment by lekoala** [comment]
build failures are not related to my change so i hope it won't be a problem to merge

**Comment by Firesphere** [comment]
This same issue has been resolved in the other PR. I'll see if I can get this one to build properly and then see where to go from there :)

**Comment by lekoala** [comment]
great! it's really a minor change anyway so it shouldn't be too difficult

**Comment by Firesphere** [comment]
Closing in favour of #107.

If accepting #107 takes too long, please ping there for a review again.

**Pull request closed without merging**
