### PR TITLE
Defaults to nullable string

### PR DESCRIPTION
**Pull request by lekoala**
Fixes https://github.com/silverleague/silverstripe-ideannotator/issues/162

### CODE REVIEW

**Comment by lekoala** [comment]
This seems to work well at first glance, it might require further checks to make sure it works as expected :)

**Comment by Firesphere** [comment]
This breaks on PHP <=8.0, it seems. Which, in itself, isn't to me a big deal, but it might break other things. I'd like to keep compatibility with 7.4 in a good state.

Maybe wrap it in a `version_compare` and return either `string` or `?string`, depending on the version?
Not ideal, but it should keep things a bit more compatible?

**Comment by lekoala** [comment]
i'm not sure why it would break anything since nullable string is supported since php 7.1 as far as i know, but i don't mind :)

**Comment by Firesphere** [comment]
It threw me errors on 7.4... ;) Not sure why either, but /shrug, if it stops complaining, I'm fine

**Pull request merged**
